# Generated by Django 3.0.7 on 2020-08-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('admin_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=60)),
                ('cno', models.IntegerField()),
                ('password', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=50)),
                ('contactno', models.IntegerField()),
                ('ps', models.CharField(max_length=30)),
            ],
        ),
    ]
