# Generated by Django 3.0.7 on 2020-08-14 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opm', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
