# Generated by Django 3.0.7 on 2020-08-16 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opm', '0005_auto_20200814_2202'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
