# Generated by Django 3.0.7 on 2020-08-16 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opm', '0008_remove_usermodel_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
