# Generated by Django 3.0.7 on 2020-08-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opm', '0010_usermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='contactno',
            field=models.IntegerField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='ps',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
