# Generated by Django 3.0.7 on 2020-08-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opm', '0011_auto_20200816_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
