# Generated by Django 3.0.7 on 2020-08-17 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opm', '0012_auto_20200816_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='contactno',
        ),
    ]
