# Generated by Django 3.0.7 on 2020-08-17 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opm', '0013_remove_usermodel_contactno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
