# Generated by Django 3.0.7 on 2020-08-17 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opm', '0015_usermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
