# Generated by Django 3.0.7 on 2020-08-18 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opm', '0016_delete_usermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=40, unique=True)),
                ('contactno', models.IntegerField(unique=True)),
                ('ps', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PhotosModel',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='opm.UserModel')),
                ('photo', models.FileField(upload_to='photos/')),
                ('captions', models.TextField()),
            ],
        ),
    ]
