# Generated by Django 3.0.7 on 2020-08-18 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opm', '0018_photosmodel_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photosmodel',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='opm.UserModel'),
        ),
    ]
