# Generated by Django 3.0.7 on 2020-08-18 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opm', '0019_auto_20200818_1144'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhotosModel',
        ),
    ]
