# Generated by Django 3.0.7 on 2020-08-18 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opm', '0021_photosmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhotosModel',
        ),
    ]
