# Generated by Django 3.0.7 on 2020-08-19 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opm', '0023_photosmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhotosModel',
        ),
    ]
