# Generated by Django 3.0.7 on 2020-08-19 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opm', '0024_delete_photosmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotosModel',
            fields=[
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='opm.UserModel')),
                ('photo', models.FileField(upload_to='photos/')),
                ('captions', models.TextField()),
                ('videos', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('text', models.TextField()),
            ],
        ),
    ]
